/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-12 07:33:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.flow;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PaymentConfermation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <form class=\"form-horizontal\" role=\"form\"  method=\"post\">\r\n");
      out.write("    <fieldset>\r\n");
      out.write("      <legend>Payment</legend>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label class=\"col-sm-3 control-label\" for=\"card-holder-name\">Name on Card</label>\r\n");
      out.write("        <div class=\"col-sm-9\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"card-holder-name\" id=\"card-holder-name\" placeholder=\"Card Holder's Name\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label class=\"col-sm-3 control-label\" for=\"card-number\">Card Number</label>\r\n");
      out.write("        <div class=\"col-sm-9\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"cardN\" id=\"card-number\" placeholder=\"Debit/Credit Card Number\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label class=\"col-sm-3 control-label\" for=\"expiry-month\">Expiration Date</label>\r\n");
      out.write("        <div class=\"col-sm-9\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xs-3\">\r\n");
      out.write("              <select class=\"form-control col-sm-2\" name=\"exM\" id=\"expiry-month\">\r\n");
      out.write("                <option>Month</option>\r\n");
      out.write("                <option value=\"01\">Jan (01)</option>\r\n");
      out.write("                <option value=\"02\">Feb (02)</option>\r\n");
      out.write("                <option value=\"03\">Mar (03)</option>\r\n");
      out.write("                <option value=\"04\">Apr (04)</option>\r\n");
      out.write("                <option value=\"05\">May (05)</option>\r\n");
      out.write("                <option value=\"06\">June (06)</option>\r\n");
      out.write("                <option value=\"07\">July (07)</option>\r\n");
      out.write("                <option value=\"08\">Aug (08)</option>\r\n");
      out.write("                <option value=\"09\">Sep (09)</option>\r\n");
      out.write("                <option value=\"10\">Oct (10)</option>\r\n");
      out.write("                <option value=\"11\">Nov (11)</option>\r\n");
      out.write("                <option value=\"12\">Dec (12)</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xs-3\">\r\n");
      out.write("              <select class=\"form-control\" name=\"exY\">\r\n");
      out.write("                <option value=\"13\">2013</option>\r\n");
      out.write("                <option value=\"14\">2014</option>\r\n");
      out.write("                <option value=\"15\">2015</option>\r\n");
      out.write("                <option value=\"16\">2016</option>\r\n");
      out.write("                <option value=\"17\">2017</option>\r\n");
      out.write("                <option value=\"18\">2018</option>\r\n");
      out.write("                <option value=\"19\">2019</option>\r\n");
      out.write("                <option value=\"20\">2020</option>\r\n");
      out.write("                <option value=\"21\">2021</option>\r\n");
      out.write("                <option value=\"22\">2022</option>\r\n");
      out.write("                <option value=\"23\">2023</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label class=\"col-sm-3 control-label\" for=\"cvv\">Card CVV</label>\r\n");
      out.write("        <div class=\"col-sm-3\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"cvN\" id=\"cvv\" placeholder=\"Security Code\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <div class=\"col-sm-offset-3 col-sm-9\">\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("     <input type=\"submit\" name=\"_eventId_submit\" class=\"subscribe btn btn-link btn-block\" ></a>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
