/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-12 07:27:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1475290371108L));
    _jspx_dependants.put("/WEB-INF/views/Footer.jsp", Long.valueOf(1475287791324L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1474651729035L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"resources/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>  \r\n");
      out.write("<html lang=\"en\">  \r\n");
      out.write("<head>  \r\n");
      out.write("  <title>Bootstrap header included</title>  \r\n");
      out.write("  <meta charset=\"utf-8\">  \r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/bootstrap.min.css\">  \r\n");
      out.write("    \r\n");
      out.write("</head>  \r\n");
      out.write("<body>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"row\">\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"col-xs-2 header-logo\">\r\n");
      out.write("<a href=\"index.jsp\"><img src=\"resources/My_Design/logo.jpg\" class=\"img-responsive\" alt=\"Cinque Terre\" width=\"200\" height=\"100\"/>\r\n");
      out.write("\r\n");
      out.write("</a></div>\r\n");
      out.write("<link href=\"resources/font/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<div class=\"col-xs-1 pull-right\">\r\n");
      out.write("          \r\n");
      out.write("                        <a href=\"#\" class=\"icoRss\" title=\"Rss\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoFacebook\" title=\"Facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoTwitter\" title=\"Twitter\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoGoogle\" title=\"Google +\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoLinkedin\" title=\"Linkedin\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("                <div class=\"pull-right\">\t\t\t\r\n");
      out.write("<a href=\"GoToCart\"><img src=\"resources/My_Design/cart11.png\" height=\"70px\" \r\n");
      out.write("                     width=\"70px\"></img></a>\r\n");
      out.write("                     <sf:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                     <center>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</center>\r\n");
      out.write("                     \r\n");
      out.write("                     </sf:if>\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("</div>        \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <nav class=\"navbar navbar-inverse\"> \r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\">  \r\n");
      out.write("    <div class=\"navbar-header\">  \r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\"> Digital Gallery</a>  \r\n");
      out.write("    </div>  \r\n");
      out.write("    <ul class=\"nav navbar-nav\">  \r\n");
      out.write("      <li class=\"active\"><a href=\"index.jsp\"><span class=\"glyphicon glyphicon-user\"></span> Home</a> \r\n");
      out.write("      <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"><span class=\"glyphicon glyphicon-th\"></span>Product Categories</a>  \r\n");
      out.write("        <ul class=\"dropdown-menu\">  \r\n");
      out.write("          <li><a href=\"DisplayProduct\">Shop Product</a></li>  \r\n");
      out.write("         \r\n");
      out.write("        </ul>  \r\n");
      out.write("      </li>  \r\n");
      out.write("      <li><a href=\"AboutUs\"><span class=\"glyphicon glyphicon-info-sign\"></span> About Us</a></li>  \r\n");
      out.write("      <li><a href=\"ContactUs\"><span class=\"glyphicon glyphicon-phone-alt\"></span> Contact Us</a></li>  \r\n");
      out.write("     \r\n");
      out.write("    </ul>  \r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">  \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </ul>  \r\n");
      out.write("  </div>  \r\n");
      out.write("</nav>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"container\">  \r\n");
      out.write("    \r\n");
      out.write("</div>  \r\n");
      out.write("<script src=\"resources/jquery.min.js\"></script>  \r\n");
      out.write("<script src=\"resources/bootstrap.min.js\"></script>  \r\n");
      out.write("</body>  \r\n");
      out.write("</html>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <center><form action=\"perform_login\" method=\"post\">\r\n");
      out.write("\t\t\t\t<h1>Login Form</h1>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Username\" required id=\"username\" name=\"username\" \r\n");
      out.write("\t\t\t\t\t\tpattern=\".{1,10}\" title=\"minimum length for username is 5\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" required id=\"password\" name=\"password\" \r\n");
      out.write("\t\t\t\t\ttitle=\"Enter Valid credentials\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Log in\" /> <a href=\"#\">Lost your\r\n");
      out.write("\t\t\t\t\t\tpassword?</a> <a href=\"usershow\">Register</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form></center>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".social:hover {\r\n");
      out.write("     -webkit-transform: scale(1.1);\r\n");
      out.write("     -moz-transform: scale(1.1);\r\n");
      out.write("     -o-transform: scale(1.1);\r\n");
      out.write(" }\r\n");
      out.write(" .social {\r\n");
      out.write("     -webkit-transform: scale(0.8);\r\n");
      out.write("     /* Browser Variations: */\r\n");
      out.write("     \r\n");
      out.write("     -moz-transform: scale(0.8);\r\n");
      out.write("     -o-transform: scale(0.8);\r\n");
      out.write("     -webkit-transition-duration: 0.5s;\r\n");
      out.write("     -moz-transition-duration: 0.5s;\r\n");
      out.write("     -o-transition-duration: 0.5s;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("    Multicoloured Hover Variations\r\n");
      out.write("*/\r\n");
      out.write(" \r\n");
      out.write(" #social-fb:hover {\r\n");
      out.write("     color: #3B5998;\r\n");
      out.write(" }\r\n");
      out.write(" #social-tw:hover {\r\n");
      out.write("     color: #4099FF;\r\n");
      out.write(" }\r\n");
      out.write(" #social-gp:hover {\r\n");
      out.write("     color: #d34836;\r\n");
      out.write(" }\r\n");
      out.write(" #social-em:hover {\r\n");
      out.write("     color: #f39c12;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" <center>\r\n");
      out.write(" ");

    Integer hitsCount =(Integer)application.getAttribute("hitCounter");
    if( hitsCount ==null || hitsCount == 0 )
    {
       /* First visit */
       out.println("Welcome to Digital Gallery");
       hitsCount = 1;
    }
    else
    {
       /* return visit */
    		  
       out.println("Welcome to Digital Gallery once again!");
       hitsCount += 1;
      
    }
    application.setAttribute("hitCounter", hitsCount);

      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("<center><b>Total number of visits: ");
      out.print( hitsCount);
      out.write("</b></center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"footer clearfix\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("       <div class=\"col-xs-6 footer-para\">\r\n");
      out.write("      <b><p>&copy; CopyRight:All Rights Reserved Designed by Digital Gallery</p></b>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"text-center center-block pull-right\">\r\n");
      out.write("            <p class=\"txt-railway\"><p><center><strong>Easy online Access</strong></center></p>\r\n");
      out.write("            <br />\r\n");
      out.write("                <a href=\"https://www.facebook.com\"><i id=\"social-fb\" class=\"fa fa-facebook-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"https://twitter.com\"><i id=\"social-tw\" class=\"fa fa-twitter-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"https://plus.google.com\"><i id=\"social-gp\" class=\"fa fa-google-plus-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"mailto:bootsnipp@gmail.com\"><i id=\"social-em\" class=\"fa fa-envelope-square fa-3x social\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(25,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.UserLoggedIn }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li>Welcome");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/header.jsp(82,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not sessionScope.UserLoggedIn}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     <li><a href=\"Login\"><span class=\"glyphicon glyphicon-log-in\"></span>SignIn</a></li>\r\n");
          out.write("      <li><a href=\"usershow\"><span class=\"glyphicon glyphicon-log-out\"></span> Sign Up</a></li>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/header.jsp(86,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.UserLoggedIn}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("       <li><a href=\"perform_logout\">Log Out </a></li>\r\n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    }
    return false;
  }
}
