/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-12 07:32:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class OrderConfermation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/views/AdminHeader.jsp", Long.valueOf(1475289076476L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1469673008000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1474651729035L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar", Long.valueOf(1474212230626L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1469673008000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fform_0026_005fmethod_005fenctype_005fcommandName_005fclass_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fmethod_005fenctype_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fmethod_005fenctype_005fcommandName_005fclass_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/My_Design/angular.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"resources/My_Design/angular.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"row\">\r\n");
      out.write("<div class =\"col-xs-2 header-logo\">\r\n");
      out.write("<a href=\"index.jsp\"><img src=\"resources/My_Design/logo.jpg\" class=\"img-responsive\" alt=\"Cinque Terre\" width=\"200\" height=\"100\"/>\r\n");
      out.write("\r\n");
      out.write("</a></div>\r\n");
      out.write("<link href=\"resources/font/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<div class=\"col-xs-1 pull-right\">\r\n");
      out.write("          \r\n");
      out.write("                        <a href=\"#\" class=\"icoRss\" title=\"Rss\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoFacebook\" title=\"Facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoTwitter\" title=\"Twitter\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoGoogle\" title=\"Google +\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoLinkedin\" title=\"Linkedin\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">DigitalGallery</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("      <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageCategory<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"category\">AddCategory</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("     \r\n");
      out.write("         <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageUser<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"usershow\">AddUser</a></li>\r\n");
      out.write("  \r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("         <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageSupplier<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"supplier\">AddSupplier</a></li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("            <li><a href=\"perform_logout\">Log Out </a></li>\r\n");
      out.write("            <li><a href=\"showproductadmin\"><span class=\"glyphicon glyphicon-hand-right\"></span> ProductAdmin</a></li>\r\n");
      out.write("              \r\n");
      out.write("       \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tvar prod3 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tangular.module('repeatSample', []).controller('repeatController',['$scope', function($scope)\r\n");
      out.write("\t\t\t {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t$scope.products = prod3;\r\n");
      out.write("\t\t\t\t$scope.value=1;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t $scope.change=function(value)\r\n");
      out.write("                 {\r\n");
      out.write("                \t $scope.products.qty=Number($scope.value);\r\n");
      out.write("                 };\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("    }]);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      if (_jspx_meth_sf_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t <div class=\"col-md-10 \">\r\n");
      out.write("   <div class=\"pull-right\">\r\n");
      out.write("<a href=\"OrderConfirmed\"><h1>Confirm your Order</h1></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                     ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sf_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_sf_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsf_005fform_0026_005fmethod_005fenctype_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    try {
      _jspx_th_sf_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fform_005f0.setParent(null);
      // /WEB-INF/views/OrderConfermation.jsp(27,0) null
      _jspx_th_sf_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
      // /WEB-INF/views/OrderConfermation.jsp(27,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setMethod("post");
      // /WEB-INF/views/OrderConfermation.jsp(27,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setAction("");
      // /WEB-INF/views/OrderConfermation.jsp(27,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setCommandName("addcart");
      // /WEB-INF/views/OrderConfermation.jsp(27,0) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setEnctype("multipart/form-data");
      int[] _jspx_push_body_count_sf_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fform_005f0 = _jspx_th_sf_005fform_005f0.doStartTag();
        if (_jspx_eval_sf_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("<div ng-app=\"repeatSample\" ng-controller=\"repeatController\">\r\n");
            out.write("<table class=\"table table-bordered table-hover table-striped\">\r\n");
            out.write("<tr>\r\n");
            out.write("\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("                        <th>Image</th>\r\n");
            out.write("                        <th>productname</th>\r\n");
            out.write("\t\t\t\t\t\t<th>Quantity</th> \r\n");
            out.write("\t\t\t\t\t\t<th>prize</th>\r\n");
            out.write("\t\t\t\t                                       \r\n");
            out.write("\t\t\t\t\t\t<th>total</th>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<tr class=\"success\" ng-repeat=\"prod in products\">\r\n");
            out.write("\t\t\t\t<td><img src=\"./resources/My_Design/{{prod.productid}}.jpg\" height=\"50px\" \r\n");
            out.write("                     width=\"50px\"></td>\r\n");
            out.write("                    <td>{{prod.productname}}</td>\r\n");
            out.write("                    \t<td>{{prod.qty}}</td>\r\n");
            out.write("                    \t\r\n");
            out.write("\t\t\t\t\t<td>{{prod.prize}}</td>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t <td>{{prod.qty*prod.prize}}</td>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("                    <td><a href=\"Removecart?pid={{prod.productid}}\">Remove</a></td>\r\n");
            out.write("                     <td>Grand Total:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.grandtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                     \r\n");
            out.write("                     \r\n");
            out.write("                     </tr>\r\n");
            out.write("                     <tr>\r\n");
            out.write("\t\t\t\t<td></td>\r\n");
            out.write("\t\t\t\t<td></td>\r\n");
            out.write("\t\t\t\t<td></td>\r\n");
            out.write("\t\t\t\t<td></td>\r\n");
            out.write("\t\t\t\t<td>Grand Total:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.grandtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t</tr>\r\n");
            out.write("                    \r\n");
            out.write("</table>\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("   \r\n");
            out.write("      \r\n");
            out.write("\r\n");
            out.write(" \r\n");
            out.write("  <center><a href=\"AddToCartgoback\">Edit</a></div></center>\r\n");
            out.write("      <br>\r\n");
            out.write("\t\t<br>\r\n");
            out.write("\t\t<br>\r\n");
            out.write("\t<b>\tCustomer Information</b>\r\n");
            out.write("      <div class=\"row\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\"> \r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<table class=\"table table-responsive\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   \r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t<thead>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<th>emailid</th>\r\n");
            out.write("\t\t\t\t\t\t<th>Mobile</th>\r\n");
            out.write("\t\t\t\t\t\t<th>Address</th>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t</thead>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${useraddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t \r\n");
            out.write("\t\t\t\t\t\t\t\t\t    \r\n");
            out.write("\t\t\t\t\t\t\t\t\t    </table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   \r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t</div> \r\n");
            out.write("\t\t\t\t\t\t ");
            int evalDoAfterBody = _jspx_th_sf_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fform_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fform_0026_005fmethod_005fenctype_005fcommandName_005fclass_005faction.reuse(_jspx_th_sf_005fform_005f0);
    }
    return false;
  }
}
