/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-12 07:30:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductAdminView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/views/AdminHeader.jsp", Long.valueOf(1475289076476L));
    _jspx_dependants.put("/WEB-INF/views/Footer.jsp", Long.valueOf(1475287791324L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1469673008000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1474651729035L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar", Long.valueOf(1474212230626L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_Of_Maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DigitalGallery/WEB-INF/lib/spring-webmvc-4.3.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1469673008000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fenctype_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmethod_005fcommandName_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fenctype_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fenctype_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.release();
    _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.release();
    _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmethod_005fcommandName_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/My_Design/angular.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"resources/My_Design/angular.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"row\">\r\n");
      out.write("<div class =\"col-xs-2 header-logo\">\r\n");
      out.write("<a href=\"index.jsp\"><img src=\"resources/My_Design/logo.jpg\" class=\"img-responsive\" alt=\"Cinque Terre\" width=\"200\" height=\"100\"/>\r\n");
      out.write("\r\n");
      out.write("</a></div>\r\n");
      out.write("<link href=\"resources/font/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<div class=\"col-xs-1 pull-right\">\r\n");
      out.write("          \r\n");
      out.write("                        <a href=\"#\" class=\"icoRss\" title=\"Rss\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoFacebook\" title=\"Facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoTwitter\" title=\"Twitter\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoGoogle\" title=\"Google +\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                        <a href=\"#\" class=\"icoLinkedin\" title=\"Linkedin\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">DigitalGallery</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("      <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageCategory<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"category\">AddCategory</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("     \r\n");
      out.write("         <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageUser<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"usershow\">AddUser</a></li>\r\n");
      out.write("  \r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("         <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">ManageSupplier<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"supplier\">AddSupplier</a></li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("            <li><a href=\"perform_logout\">Log Out </a></li>\r\n");
      out.write("            <li><a href=\"showproductadmin\"><span class=\"glyphicon glyphicon-hand-right\"></span> ProductAdmin</a></li>\r\n");
      out.write("              \r\n");
      out.write("       \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar prod1 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tvar prod2 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tvar prod3 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tangular.module('repeatSample', []).controller('repeatController',\r\n");
      out.write("\t\t\tfunction($scope) {\r\n");
      out.write("\t\t\t\t$scope.mylist1 = prod1;\r\n");
      out.write("\t\t\t\t$scope.mylist2 = prod2;\r\n");
      out.write("\t\t\t\t$scope.mylist3 = prod3;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$scope.sort = function(keyname) {\r\n");
      out.write("\t\t\t\t\t$scope.sortKey = keyname; //set the sortKey to the param passed\r\n");
      out.write("\t\t\t\t\t$scope.reverse = !$scope.reverse; //if true make it false and vice versa\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div ng-controller=\"repeatController\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"input-group col-md-12\">\r\n");
      out.write("\r\n");
      out.write("<h2 align=\"center\">Search Products</h2>\r\n");
      out.write("<input type=\"text\" class=\"search-query form-control\" placeholder=\"Search\" ng-model=\"searchText\" />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div ng-controller=\"repeatController\">\r\n");
      out.write("<table class=\"table table-responsive\">\r\n");
      out.write("<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>productid</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th>productname</th>\r\n");
      out.write("\t\t\t\t\t\t<th>prize</th>\r\n");
      out.write("\t\t\t\t\t\t<th>stock</th>\r\n");
      out.write("\t\t\t\t\t\t<th>categoryid</th>\r\n");
      out.write("\t\t\t\t\t\t<th>supplierid</th>\r\n");
      out.write("\t\t\t\t\t\t<th>discrption</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Image</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tr ng-repeat=\"product in mylist3|filter:searchText\">\r\n");
      out.write("\t\t\t\t<td><a href=\"ProductDescription?pid={{product.productid}}\">{{product.productid}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.productname}}\">{{product.productname}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.prize}}\">{{product.prize}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.stock}}\">{{product.stock}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.categoryid}}\">{{product.categoryid}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.supplierid}}\">{{product.supplierid}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"ProductDescription?pid={{product.discrption}}\">{{product.discrption}}</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"Deleteproduct?pid={{product.productid}}\">Delete</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"plzUpdatedproduct?pid={{product.productid}}\"><img src=\"./resources/My_Design/{{product.productid}}.jpg\" height=\"50px\" \r\n");
      out.write("                     width=\"50px\">Update</a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".social:hover {\r\n");
      out.write("     -webkit-transform: scale(1.1);\r\n");
      out.write("     -moz-transform: scale(1.1);\r\n");
      out.write("     -o-transform: scale(1.1);\r\n");
      out.write(" }\r\n");
      out.write(" .social {\r\n");
      out.write("     -webkit-transform: scale(0.8);\r\n");
      out.write("     /* Browser Variations: */\r\n");
      out.write("     \r\n");
      out.write("     -moz-transform: scale(0.8);\r\n");
      out.write("     -o-transform: scale(0.8);\r\n");
      out.write("     -webkit-transition-duration: 0.5s;\r\n");
      out.write("     -moz-transition-duration: 0.5s;\r\n");
      out.write("     -o-transition-duration: 0.5s;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("    Multicoloured Hover Variations\r\n");
      out.write("*/\r\n");
      out.write(" \r\n");
      out.write(" #social-fb:hover {\r\n");
      out.write("     color: #3B5998;\r\n");
      out.write(" }\r\n");
      out.write(" #social-tw:hover {\r\n");
      out.write("     color: #4099FF;\r\n");
      out.write(" }\r\n");
      out.write(" #social-gp:hover {\r\n");
      out.write("     color: #d34836;\r\n");
      out.write(" }\r\n");
      out.write(" #social-em:hover {\r\n");
      out.write("     color: #f39c12;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" <center>\r\n");
      out.write(" ");

    Integer hitsCount =(Integer)application.getAttribute("hitCounter");
    if( hitsCount ==null || hitsCount == 0 )
    {
       /* First visit */
       out.println("Welcome to Digital Gallery");
       hitsCount = 1;
    }
    else
    {
       /* return visit */
    		  
       out.println("Welcome to Digital Gallery once again!");
       hitsCount += 1;
      
    }
    application.setAttribute("hitCounter", hitsCount);

      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("<center><b>Total number of visits: ");
      out.print( hitsCount);
      out.write("</b></center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"footer clearfix\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("       <div class=\"col-xs-6 footer-para\">\r\n");
      out.write("      <b><p>&copy; CopyRight:All Rights Reserved Designed by Digital Gallery</p></b>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"text-center center-block pull-right\">\r\n");
      out.write("            <p class=\"txt-railway\"><p><center><strong>Easy online Access</strong></center></p>\r\n");
      out.write("            <br />\r\n");
      out.write("                <a href=\"https://www.facebook.com\"><i id=\"social-fb\" class=\"fa fa-facebook-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"https://twitter.com\"><i id=\"social-tw\" class=\"fa fa-twitter-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"https://plus.google.com\"><i id=\"social-gp\" class=\"fa fa-google-plus-square fa-3x social\"></i></a>\r\n");
      out.write("\t            <a href=\"mailto:bootsnipp@gmail.com\"><i id=\"social-em\" class=\"fa fa-envelope-square fa-3x social\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/ProductAdminView.jsp(26,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!checkk}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("<div class=\"container\" ng-app=\"repeatSample\">\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"row\">\r\n");
          out.write("\t\t<div\r\n");
          out.write("\t\t\tclass=\"col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_sf_005fform_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_sf_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fenctype_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    try {
      _jspx_th_sf_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(33,3) null
      _jspx_th_sf_005fform_005f0.setDynamicAttribute(null, "role", "form");
      // /WEB-INF/views/ProductAdminView.jsp(33,3) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setAction("insertproduct");
      // /WEB-INF/views/ProductAdminView.jsp(33,3) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setCommandName("productadmin");
      // /WEB-INF/views/ProductAdminView.jsp(33,3) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setMethod("post");
      // /WEB-INF/views/ProductAdminView.jsp(33,3) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setModelAttribute("productadmin");
      // /WEB-INF/views/ProductAdminView.jsp(33,3) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setEnctype("multipart/form-data");
      int[] _jspx_push_body_count_sf_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fform_005f0 = _jspx_th_sf_005fform_005f0.doStartTag();
        if (_jspx_eval_sf_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<h2>\r\n");
            out.write("\t\t\t\t\tPlease See the all Products<small>It's All and always will\r\n");
            out.write("\t\t\t\t\t\tbe for Admin</small>\r\n");
            out.write("\t\t\t\t</h2>\r\n");
            out.write("\t\t\t\t<hr class=\"colorgraph\">\r\n");
            out.write("\t\t\t\t<div class=\"row\">\r\n");
            out.write("\t\t\t\t\t<div class=\"row\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
            out.write("\t\t\t\t\t\t   <div class=\"form-group col-xs-12\">\r\n");
            out.write("\t\t\t\t\t\t    \r\n");
            out.write("                                 ");
            if (_jspx_meth_sf_005finput_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t   \r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f2(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f3(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t<div class=\"form-group col-xs-12\">\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f4(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t   <div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005flabel_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005fselect_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t   </div>\r\n");
            out.write("\t\t\t   \r\n");
            out.write("\t\t\t      <div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005flabel_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005fselect_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t   </div>\r\n");
            out.write("\t\t\t   \r\n");
            out.write("\t\t\t   \r\n");
            out.write("\t\t\t   <div class=\"col-xs-12\">\r\n");
            out.write("\t\t\t\t<input type=\"submit\" value=\"Get-Products\"\r\n");
            out.write("\t\t\t\tclass=\"btn btn-primary btn-block btn-lg\" tabindex=\"7\">\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t   </div>\t   \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_sf_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fform_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fenctype_005fcommandName_005faction.reuse(_jspx_th_sf_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(44,33) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "type", "file");
      // /WEB-INF/views/ProductAdminView.jsp(44,33) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setPath("pimage");
      // /WEB-INF/views/ProductAdminView.jsp(44,33) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(44,33) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "placeholder", "file");
      // /WEB-INF/views/ProductAdminView.jsp(44,33) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(44,33) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setTitle("minimum length for ProductDiscription is 1");
      int[] _jspx_push_body_count_sf_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f0 = _jspx_th_sf_005finput_005f0.doStartTag();
        if (_jspx_th_sf_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(49,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setPath("productname");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "placeholder", "productname");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(49,7) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setTitle("minimum length for productname is 5");
      int[] _jspx_push_body_count_sf_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f1 = _jspx_th_sf_005finput_005f1.doStartTag();
        if (_jspx_th_sf_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(55,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setPath("prize");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) null
      _jspx_th_sf_005finput_005f2.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) null
      _jspx_th_sf_005finput_005f2.setDynamicAttribute(null, "placeholder", "prize");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) null
      _jspx_th_sf_005finput_005f2.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) null
      _jspx_th_sf_005finput_005f2.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(55,6) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setTitle("minimum length for prize is 1");
      int[] _jspx_push_body_count_sf_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f2 = _jspx_th_sf_005finput_005f2.doStartTag();
        if (_jspx_th_sf_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(62,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setPath("stock");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "placeholder", "stock");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(62,5) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setTitle("minimum length for stock is 1");
      int[] _jspx_push_body_count_sf_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f3 = _jspx_th_sf_005finput_005f3.doStartTag();
        if (_jspx_th_sf_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(68,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setPath("discrption");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "placeholder", "discrption");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(68,4) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setTitle("minimum length for ProductDiscription is 1");
      int[] _jspx_push_body_count_sf_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f4 = _jspx_th_sf_005finput_005f4.doStartTag();
        if (_jspx_th_sf_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f4.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005flabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_sf_005flabel_005f0 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    try {
      _jspx_th_sf_005flabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005flabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(75,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005flabel_005f0.setPath("categoryid");
      int[] _jspx_push_body_count_sf_005flabel_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005flabel_005f0 = _jspx_th_sf_005flabel_005f0.doStartTag();
        if (_jspx_eval_sf_005flabel_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("categoryid");
            int evalDoAfterBody = _jspx_th_sf_005flabel_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005flabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005flabel_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005flabel_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005flabel_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.reuse(_jspx_th_sf_005flabel_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sf_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_sf_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(76,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fselect_005f0.setPath("categoryid");
      // /WEB-INF/views/ProductAdminView.jsp(76,5) null
      _jspx_th_sf_005fselect_005f0.setDynamicAttribute(null, "class", "form-control input-sm");
      // /WEB-INF/views/ProductAdminView.jsp(76,5) null
      _jspx_th_sf_005fselect_005f0.setDynamicAttribute(null, "ng-controller", "repeatController");
      int[] _jspx_push_body_count_sf_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fselect_005f0 = _jspx_th_sf_005fselect_005f0.doStartTag();
        if (_jspx_eval_sf_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t  <option ng-repeat=\"product in mylist1\" value=\"{{product.categoryid}}\">{{product.categoryName}}</option>\r\n");
            out.write("\t\t\t  ");
            int evalDoAfterBody = _jspx_th_sf_005fselect_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fselect_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.reuse(_jspx_th_sf_005fselect_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005flabel_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_sf_005flabel_005f1 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    try {
      _jspx_th_sf_005flabel_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005flabel_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(82,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005flabel_005f1.setPath("supplierid");
      int[] _jspx_push_body_count_sf_005flabel_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005flabel_005f1 = _jspx_th_sf_005flabel_005f1.doStartTag();
        if (_jspx_eval_sf_005flabel_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("supplierid");
            int evalDoAfterBody = _jspx_th_sf_005flabel_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005flabel_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005flabel_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005flabel_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005flabel_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.reuse(_jspx_th_sf_005flabel_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fselect_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sf_005fselect_005f1 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_sf_005fselect_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fselect_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/ProductAdminView.jsp(83,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fselect_005f1.setPath("supplierid");
      // /WEB-INF/views/ProductAdminView.jsp(83,5) null
      _jspx_th_sf_005fselect_005f1.setDynamicAttribute(null, "class", "form-control input-sm");
      // /WEB-INF/views/ProductAdminView.jsp(83,5) null
      _jspx_th_sf_005fselect_005f1.setDynamicAttribute(null, "ng-controller", "repeatController");
      int[] _jspx_push_body_count_sf_005fselect_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fselect_005f1 = _jspx_th_sf_005fselect_005f1.doStartTag();
        if (_jspx_eval_sf_005fselect_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t  <option ng-repeat=\"product in mylist2\" value=\"{{product.supplierid}}\">{{product.suppliername}}</option>\r\n");
            out.write("\t\t\t  ");
            int evalDoAfterBody = _jspx_th_sf_005fselect_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fselect_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fselect_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fselect_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.reuse(_jspx_th_sf_005fselect_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/ProductAdminView.jsp(102,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkk}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("<div class=\"container\" ng-app=\"repeatSample\">\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"row\">\r\n");
          out.write("\t\t<div\r\n");
          out.write("\t\t\tclass=\"col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_sf_005fform_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fform_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_sf_005fform_005f1 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    try {
      _jspx_th_sf_005fform_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fform_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(109,3) null
      _jspx_th_sf_005fform_005f1.setDynamicAttribute(null, "role", "form");
      // /WEB-INF/views/ProductAdminView.jsp(109,3) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f1.setAction("plzNowUpdatedproducts");
      // /WEB-INF/views/ProductAdminView.jsp(109,3) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f1.setCommandName("productadmin");
      // /WEB-INF/views/ProductAdminView.jsp(109,3) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f1.setMethod("post");
      int[] _jspx_push_body_count_sf_005fform_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fform_005f1 = _jspx_th_sf_005fform_005f1.doStartTag();
        if (_jspx_eval_sf_005fform_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<h2>\r\n");
            out.write("\t\t\t\t\tPlease Update Products<small>It's All and always will\r\n");
            out.write("\t\t\t\t\t\tbe for Admin</small>\r\n");
            out.write("\t\t\t\t</h2>\r\n");
            out.write("\t\t\t\t<hr class=\"colorgraph\">\r\n");
            out.write("\t\t\t\t<div class=\"row\">\r\n");
            out.write("\t\t\t\t\t<div class=\"row\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"form-group col-xs-12\">\r\n");
            out.write("\t\t\t\t\t\t   ");
            if (_jspx_meth_sf_005finput_005f5(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f6(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f7(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f8(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f9(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t<div class=\"form-group col-xs-12\">\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f10(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t   <div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005flabel_005f2(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005fselect_005f2(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t   </div>\r\n");
            out.write("\t\t\t   \r\n");
            out.write("\t\t\t      <div class=\"form-group col-xs-6\">\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005flabel_005f3(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t  ");
            if (_jspx_meth_sf_005fselect_005f3(_jspx_th_sf_005fform_005f1, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t   </div>\r\n");
            out.write("\t\t\t   \r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t   <div class=\"col-xs-12\">\r\n");
            out.write("\t\t\t\t<input type=\"submit\" value=\"Get-Update-Products\"\r\n");
            out.write("\t\t\t\tclass=\"btn btn-primary btn-block btn-lg\" tabindex=\"7\">\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t   </div>\t   \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_sf_005fform_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fform_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fform_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fform_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fform_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fform_0026_005frole_005fmethod_005fcommandName_005faction.reuse(_jspx_th_sf_005fform_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f5.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(119,9) null
      _jspx_th_sf_005finput_005f5.setDynamicAttribute(null, "type", "file");
      // /WEB-INF/views/ProductAdminView.jsp(119,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f5.setPath("pimage");
      // /WEB-INF/views/ProductAdminView.jsp(119,9) null
      _jspx_th_sf_005finput_005f5.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(119,9) null
      _jspx_th_sf_005finput_005f5.setDynamicAttribute(null, "placeholder", "file");
      // /WEB-INF/views/ProductAdminView.jsp(119,9) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f5.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(119,9) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f5.setTitle("minimum length for ProductDiscription is 1");
      int[] _jspx_push_body_count_sf_005finput_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f5 = _jspx_th_sf_005finput_005f5.doStartTag();
        if (_jspx_th_sf_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f5.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005ftitle_005ftabindex_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f6.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(125,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f6.setPath("productid");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) null
      _jspx_th_sf_005finput_005f6.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) null
      _jspx_th_sf_005finput_005f6.setDynamicAttribute(null, "placeholder", "productid");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f6.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) null
      _jspx_th_sf_005finput_005f6.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) null
      _jspx_th_sf_005finput_005f6.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(125,6) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f6.setTitle("minimum length for productid is 5");
      int[] _jspx_push_body_count_sf_005finput_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f6 = _jspx_th_sf_005finput_005f6.doStartTag();
        if (_jspx_th_sf_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f6.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f7.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(131,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f7.setPath("productname");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) null
      _jspx_th_sf_005finput_005f7.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) null
      _jspx_th_sf_005finput_005f7.setDynamicAttribute(null, "placeholder", "productname");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f7.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) null
      _jspx_th_sf_005finput_005f7.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) null
      _jspx_th_sf_005finput_005f7.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(131,7) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f7.setTitle("minimum length for productname is 5");
      int[] _jspx_push_body_count_sf_005finput_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f7 = _jspx_th_sf_005finput_005f7.doStartTag();
        if (_jspx_th_sf_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f7.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f8 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f8.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(137,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f8.setPath("prize");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) null
      _jspx_th_sf_005finput_005f8.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) null
      _jspx_th_sf_005finput_005f8.setDynamicAttribute(null, "placeholder", "prize");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f8.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) null
      _jspx_th_sf_005finput_005f8.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) null
      _jspx_th_sf_005finput_005f8.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(137,6) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f8.setTitle("minimum length for prize is 1");
      int[] _jspx_push_body_count_sf_005finput_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f8 = _jspx_th_sf_005finput_005f8.doStartTag();
        if (_jspx_th_sf_005finput_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f8.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f9 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f9.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(144,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f9.setPath("stock");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) null
      _jspx_th_sf_005finput_005f9.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) null
      _jspx_th_sf_005finput_005f9.setDynamicAttribute(null, "placeholder", "stock");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f9.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) null
      _jspx_th_sf_005finput_005f9.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) null
      _jspx_th_sf_005finput_005f9.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(144,5) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f9.setTitle("minimum length for stock is 1");
      int[] _jspx_push_body_count_sf_005finput_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f9 = _jspx_th_sf_005finput_005f9.doStartTag();
        if (_jspx_th_sf_005finput_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f9.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f10 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f10.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(150,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f10.setPath("discrption");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) null
      _jspx_th_sf_005finput_005f10.setDynamicAttribute(null, "class", "form-control input-lg");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) null
      _jspx_th_sf_005finput_005f10.setDynamicAttribute(null, "placeholder", "discrption");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f10.setTabindex("1");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) null
      _jspx_th_sf_005finput_005f10.setDynamicAttribute(null, "pattern", ".{1,15}");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) null
      _jspx_th_sf_005finput_005f10.setDynamicAttribute(null, "required", "true");
      // /WEB-INF/views/ProductAdminView.jsp(150,4) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f10.setTitle("minimum length for ProductDiscription is 1");
      int[] _jspx_push_body_count_sf_005finput_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f10 = _jspx_th_sf_005finput_005f10.doStartTag();
        if (_jspx_th_sf_005finput_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f10.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftitle_005ftabindex_005frequired_005fplaceholder_005fpattern_005fpath_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005flabel_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_sf_005flabel_005f2 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    try {
      _jspx_th_sf_005flabel_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sf_005flabel_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(157,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005flabel_005f2.setPath("categoryid");
      int[] _jspx_push_body_count_sf_005flabel_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005flabel_005f2 = _jspx_th_sf_005flabel_005f2.doStartTag();
        if (_jspx_eval_sf_005flabel_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("categoryid");
            int evalDoAfterBody = _jspx_th_sf_005flabel_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005flabel_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005flabel_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005flabel_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005flabel_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.reuse(_jspx_th_sf_005flabel_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fselect_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sf_005fselect_005f2 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_sf_005fselect_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fselect_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(158,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fselect_005f2.setPath("categoryid");
      // /WEB-INF/views/ProductAdminView.jsp(158,5) null
      _jspx_th_sf_005fselect_005f2.setDynamicAttribute(null, "class", "form-control input-sm");
      // /WEB-INF/views/ProductAdminView.jsp(158,5) null
      _jspx_th_sf_005fselect_005f2.setDynamicAttribute(null, "ng-controller", "repeatController");
      int[] _jspx_push_body_count_sf_005fselect_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fselect_005f2 = _jspx_th_sf_005fselect_005f2.doStartTag();
        if (_jspx_eval_sf_005fselect_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t  <option ng-repeat=\"product in mylist1\" value=\"{{product.categoryid}}\">{{product.categoryName}}</option>\r\n");
            out.write("\t\t\t  ");
            int evalDoAfterBody = _jspx_th_sf_005fselect_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fselect_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fselect_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fselect_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fselect_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.reuse(_jspx_th_sf_005fselect_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005flabel_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_sf_005flabel_005f3 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    try {
      _jspx_th_sf_005flabel_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sf_005flabel_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(164,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005flabel_005f3.setPath("supplierid");
      int[] _jspx_push_body_count_sf_005flabel_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005flabel_005f3 = _jspx_th_sf_005flabel_005f3.doStartTag();
        if (_jspx_eval_sf_005flabel_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("supplierid");
            int evalDoAfterBody = _jspx_th_sf_005flabel_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005flabel_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005flabel_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005flabel_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005flabel_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005flabel_0026_005fpath.reuse(_jspx_th_sf_005flabel_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fselect_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sf_005fselect_005f3 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_sf_005fselect_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fselect_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f1);
      // /WEB-INF/views/ProductAdminView.jsp(165,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fselect_005f3.setPath("supplierid");
      // /WEB-INF/views/ProductAdminView.jsp(165,5) null
      _jspx_th_sf_005fselect_005f3.setDynamicAttribute(null, "class", "form-control input-sm");
      // /WEB-INF/views/ProductAdminView.jsp(165,5) null
      _jspx_th_sf_005fselect_005f3.setDynamicAttribute(null, "ng-controller", "repeatController");
      int[] _jspx_push_body_count_sf_005fselect_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fselect_005f3 = _jspx_th_sf_005fselect_005f3.doStartTag();
        if (_jspx_eval_sf_005fselect_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t  <option ng-repeat=\"product in mylist2\" value=\"{{product.supplierid}}\">{{product.suppliername}}</option>\r\n");
            out.write("\t\t\t  ");
            int evalDoAfterBody = _jspx_th_sf_005fselect_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fselect_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fselect_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fselect_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fselect_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fng_002dcontroller_005fclass.reuse(_jspx_th_sf_005fselect_005f3);
    }
    return false;
  }
}
